CUDA_VISIBLE_DEVICES=0 python run.py \
    --output_dir=saved_models/FreeLB/ \
    --config_name=microsoft/graphcodebert-base \
    --model_name_or_path=microsoft/graphcodebert-base \
    --tokenizer_name=microsoft/graphcodebert-base \
    --do_test \
    --train_data_file=../dataset/train.jsonl \
    --eval_data_file=../dataset/valid.jsonl \
    --test_data_file=/home/fdse/sjw/attack/attack_csv/defect/graphcodebert/ori/test_adv_coda.jsonl \
    --epoch 5 \
    --code_length 448 \
    --data_flow_length 64 \
    --train_batch_size 16 \
    --eval_batch_size 32 \
    --learning_rate 2e-5 \
    --max_grad_norm 1.0 \
    --evaluate_during_training \
    --seed 5 2>&1| tee saved_models/train.log
